//-----------------------------------------------------------------------
// <copyright file = "AscribedGameApiControlCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.AscribedGameApiControl;

    /// <summary>
    /// Implementation of the F2X <see cref="AscribedGameApiControl"/> category.
    /// Ascribed Game API Control category of messages for controlling API negotiations related to a game theme or game
    /// shell.
    /// Category: 3027; Major Version: 1
    /// </summary>
    public class AscribedGameApiControlCategory : F2XCategoryBase<AscribedGameApiControl>
    {
        #region Fields

        /// <summary>
        /// Object which implements the AscribedGameApiControlCategory callbacks.
        /// </summary>
        private readonly IAscribedGameApiControlCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="AscribedGameApiControlCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// AscribedGameApiControlCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public AscribedGameApiControlCategory(IF2XTransport transport, IAscribedGameApiControlCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<GetAscribedGameApiVersionsSend>(HandleGetAscribedGameApiVersions);
            AddMessagehandler<SetAscribedGameApiVersionsSend>(HandleSetAscribedGameApiVersions);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.AscribedGameApiControl;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the GetAscribedGameApiVersionsSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleGetAscribedGameApiVersions(GetAscribedGameApiVersionsSend message)
        {
            GetAscribedGameApiVersionsReplyContentCategoryVersions callbackResult;
            var errorMessage = callbackHandler.ProcessGetAscribedGameApiVersions(message.AscribedGame, message.Extensions, out callbackResult);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<GetAscribedGameApiVersionsReply>(errorCode, errorMessage);
            var reply = (GetAscribedGameApiVersionsReply)replyMessage.Message.Item;
            reply.Content.CategoryVersions = callbackResult;
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the SetAscribedGameApiVersionsSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleSetAscribedGameApiVersions(SetAscribedGameApiVersionsSend message)
        {
            bool callbackResult;
            var errorMessage = callbackHandler.ProcessSetAscribedGameApiVersions(message.CategoryVersions, out callbackResult);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<SetAscribedGameApiVersionsReply>(errorCode, errorMessage);
            var reply = (SetAscribedGameApiVersionsReply)replyMessage.Message.Item;
            reply.Content.CategoriesAccepted = callbackResult;
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

