//-----------------------------------------------------------------------
// <copyright file = "CallAttendantCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.CallAttendant;

    /// <summary>
    /// Implementation of the F2X <see cref="CallAttendant"/> category.
    /// The CallAttendant category of messages is used to call the attendant.
    /// Category: 149; Major Version: 1
    /// </summary>
    public class CallAttendantCategory : F2XTransactionalCategoryBase<CallAttendant>, ICallAttendantCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="CallAttendantCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public CallAttendantCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.CallAttendant;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region ICallAttendantCategory Members

        /// <inheritdoc/>
        public void ClearPriorityCallAttendant()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<ClearPriorityCallAttendantSend>();

            var reply = SendMessageAndGetReply<ClearPriorityCallAttendantReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        /// <inheritdoc/>
        public void SetPriorityCallAttendant(bool ignoreLamps)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<SetPriorityCallAttendantSend>();
            var content = (SetPriorityCallAttendantSend)request.Message.Item;
            content.IgnoreLamps = ignoreLamps;

            var reply = SendMessageAndGetReply<SetPriorityCallAttendantReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        #endregion

    }

}

