//-----------------------------------------------------------------------
// <copyright file = "CashoutCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.Cashout;
    using Schemas.Internal.Types;

    /// <summary>
    /// Implementation of the F2X <see cref="Cashout"/> category.
    /// Cashout category of messages. Implements closed-loop cashouts.
    /// Category: 146; Major Version: 1
    /// </summary>
    public class CashoutCategory : F2XTransactionalCategoryBase<Cashout>, ICashoutCategory
    {
        #region Fields

        /// <summary>
        /// Object which implements the CashoutCategory callbacks.
        /// </summary>
        private readonly ICashoutCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="CashoutCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// CashoutCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public CashoutCategory(IF2XTransport transport, ICashoutCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<CashoutStatusSend>(HandleStatus);
            AddMessagehandler<UpdatePropertiesSend>(HandleUpdateProperties);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.Cashout;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region ICashoutCategory Members

        /// <inheritdoc/>
        public Properties GetProperties()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetPropertiesSend>();

            var reply = SendMessageAndGetReply<GetPropertiesReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.Properties;
        }

        /// <inheritdoc/>
        public RequestCashoutReplyContent RequestCashout(bool allowPlayerCancel)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<RequestCashoutSend>();
            var content = (RequestCashoutSend)request.Message.Item;
            content.AllowPlayerCancel = allowPlayerCancel;

            var reply = SendMessageAndGetReply<RequestCashoutReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        /// <inheritdoc/>
        public RequestPartialCashoutReplyContent RequestPartialCashout(Amount cashoutAmount, bool allowPlayerCancel)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<RequestPartialCashoutSend>();
            var content = (RequestPartialCashoutSend)request.Message.Item;
            content.CashoutAmount = cashoutAmount;
            content.AllowPlayerCancel = allowPlayerCancel;

            var reply = SendMessageAndGetReply<RequestPartialCashoutReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the CashoutStatusSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleStatus(CashoutStatusSend message)
        {
            var errorMessage = callbackHandler.ProcessStatus(message.CashoutId, message.Status, message.RequestedAmount, message.CashedOutAmount);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<CashoutStatusReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the UpdatePropertiesSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleUpdateProperties(UpdatePropertiesSend message)
        {
            var errorMessage = callbackHandler.ProcessUpdateProperties(message.Properties);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<UpdatePropertiesReply>(errorCode, errorMessage);
            SendFoundationNonTransactionalChannelResponse(replyMessage);
        }

        #endregion

    }

}

