//-----------------------------------------------------------------------
// <copyright file = "CoplayerManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using System.Collections.Generic;
    using F2XTransport;
    using Schemas.Internal.CoplayerManagement;

    /// <summary>
    /// Implementation of the F2X <see cref="CoplayerManagement"/> category.
    /// F2X Coplayer Management category of messages.
    /// Category: 1012; Major Version: 1
    /// </summary>
    public class CoplayerManagementCategory : F2XTransactionalCategoryBase<CoplayerManagement>, ICoplayerManagementCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="CoplayerManagementCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public CoplayerManagementCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.CoplayerManagement;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region ICoplayerManagementCategory Members

        /// <inheritdoc/>
        public void BindCoplayerSession(int coplayer, int session)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<BindCoplayerSessionSend>();
            var content = (BindCoplayerSessionSend)request.Message.Item;
            content.Coplayer = coplayer;
            content.Session = session;

            var reply = SendMessageAndGetReply<BindCoplayerSessionReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        /// <inheritdoc/>
        public IEnumerable<int> CreateCoplayers(int numberOfCoplayers)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<CreateCoplayersSend>();
            var content = (CreateCoplayersSend)request.Message.Item;
            content.NumberOfCoplayers = numberOfCoplayers;

            var reply = SendMessageAndGetReply<CreateCoplayersReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        /// <inheritdoc/>
        public int GetConfigDataMaxNumOfCoplayers()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetConfigDataMaxNumOfCoplayersSend>();

            var reply = SendMessageAndGetReply<GetConfigDataMaxNumOfCoplayersReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.MaxNumOfCoplayers;
        }

        /// <inheritdoc/>
        public IEnumerable<CoplayerInstance> GetCoplayers()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetCoplayersSend>();

            var reply = SendMessageAndGetReply<GetCoplayersReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        #endregion

    }

}

