//-----------------------------------------------------------------------
// <copyright file = "EventLogCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.EventLog;

    /// <summary>
    /// Implementation of the F2X <see cref="EventLog"/> category.
    /// The EventLog category of messages records events provided by the client.
    /// Category: 143; Major Version: 1
    /// </summary>
    public class EventLogCategory : F2XTransactionalCategoryBase<EventLog>, IEventLogCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="EventLogCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public EventLogCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.EventLog;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IEventLogCategory Members

        /// <inheritdoc/>
        public void RecordEvent(SourceSelector sourceSelector, string eventText)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<RecordEventSend>();
            var content = (RecordEventSend)request.Message.Item;
            content.SourceSelector = sourceSelector;
            content.EventText = eventText;

            var reply = SendMessageAndGetReply<RecordEventReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        #endregion

    }

}

