//-----------------------------------------------------------------------
// <copyright file = "FlashPlayerClockCategory.cs" company = "IGT">
//     Copyright (c) 2022 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.FlashPlayerClock;

    /// <summary>
    /// Implementation of the F2X <see cref="FlashPlayerClock"/> category.
    /// This category contains messages that support (Macau) requirements for flashing the player facing clock under
    /// specific conditions.
    /// Category: 159; Major Version: 1
    /// </summary>
    public class FlashPlayerClockCategory : F2XTransactionalCategoryBase<FlashPlayerClock>, IFlashPlayerClockCategory
    {
        #region Fields

        /// <summary>
        /// Object which implements the FlashPlayerClockCategory callbacks.
        /// </summary>
        private readonly IFlashPlayerClockCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="FlashPlayerClockCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// FlashPlayerClockCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public FlashPlayerClockCategory(IF2XTransport transport, IFlashPlayerClockCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<UpdateFlashPlayerClockPropertiesSend>(HandleUpdateFlashPlayerClockProperties);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.FlashPlayerClock;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IFlashPlayerClockCategory Members

        /// <inheritdoc/>
        public ConfigData GetConfigData()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetConfigDataSend>();

            var reply = SendMessageAndGetReply<GetConfigDataReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.ConfigData;
        }

        /// <inheritdoc/>
        public FlashPlayerClockProperties GetFlashPlayerClockProperties()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetFlashPlayerClockPropertiesSend>();

            var reply = SendMessageAndGetReply<GetFlashPlayerClockPropertiesReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.FlashPlayerClockProperties;
        }

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the UpdateFlashPlayerClockPropertiesSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleUpdateFlashPlayerClockProperties(UpdateFlashPlayerClockPropertiesSend message)
        {
            var errorMessage = callbackHandler.ProcessUpdateFlashPlayerClockProperties(message.FlashPlayerClockProperties);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<UpdateFlashPlayerClockPropertiesReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

