//-----------------------------------------------------------------------
// <copyright file = "GameProgressiveSettingsCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using F2XTransport;
    using Schemas.Internal.GameProgressiveSettings;

    /// <summary>
    /// Implementation of the F2X <see cref="GameProgressiveSettings"/> category.
    /// This category provides messages for the game clients to query linked progressive settings during an active theme
    /// context.  Note: The progressive settings do not change during an active theme context.
    /// Category: 1024; Major Version: 1
    /// </summary>
    public class GameProgressiveSettingsCategory : F2XTransactionalCategoryBase<GameProgressiveSettings>, IGameProgressiveSettingsCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="GameProgressiveSettingsCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public GameProgressiveSettingsCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.GameProgressiveSettings;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IGameProgressiveSettingsCategory Members

        /// <inheritdoc/>
        public IEnumerable<GameLevelProgressiveSettings> QueryProgressiveSettings()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<QueryProgressiveSettingsSend>();

            var reply = SendMessageAndGetReply<QueryProgressiveSettingsReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        #endregion

    }

}

