//-----------------------------------------------------------------------
// <copyright file = "GameGroupInformationCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using System.Linq;
    using F2XTransport;
    using Schemas.Internal.GameGroupInformation;
    using Schemas.Internal.Types;

    /// <summary>
    /// Implementation of the F2X <see cref="GameGroupInformation"/> category.
    /// Game Group category of messages. Category: 122, Version: 1
    /// This category is used to request game group specific data.
    /// </summary>
    public class GameGroupInformationCategory : F2XTransactionalCategoryBase<GameGroupInformation>, IGameGroupInformationCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="GameGroupInformationCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public GameGroupInformationCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.GameGroupInformation;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IGameGroupInformationCategory Members

        /// <inheritdoc/>
        public IEnumerable<ThemePayvarGroups> GetPayvarGroupsForTheme(IEnumerable<ThemeIdentifier> theme)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetPayvarGroupsForThemeSend>();
            var content = (GetPayvarGroupsForThemeSend)request.Message.Item;
            content.Theme = theme.ToList();

            var reply = SendMessageAndGetReply<GetPayvarGroupsForThemeReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        #endregion

    }

}

