//-----------------------------------------------------------------------
// <copyright file = "GamePlayStatusCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.GamePlayStatus;

    /// <summary>
    /// Implementation of the F2X <see cref="GamePlayStatus"/> category.
    /// GamePlayStatus category of messages for the Bin to query the game play status, and get notification from the
    /// Foundation when any of the game play status has changed.
    /// Category: 1032; Major Version: 1
    /// </summary>
    public class GamePlayStatusCategory : F2XTransactionalCategoryBase<GamePlayStatus>, IGamePlayStatusCategory
    {
        #region Fields

        /// <summary>
        /// Object which implements the GamePlayStatusCategory callbacks.
        /// </summary>
        private readonly IGamePlayStatusCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="GamePlayStatusCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// GamePlayStatusCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public GamePlayStatusCategory(IF2XTransport transport, IGamePlayStatusCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<GameFocusChangedSend>(HandleGameFocusChanged);
            AddMessagehandler<GameInProgressChangedSend>(HandleGameInProgressChanged);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.GamePlayStatus;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IGamePlayStatusCategory Members

        /// <inheritdoc/>
        public GameFocus GetGameFocus()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetGameFocusSend>();

            var reply = SendMessageAndGetReply<GetGameFocusReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.GameFocus;
        }

        /// <inheritdoc/>
        public bool GetGameInProgress()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetGameInProgressSend>();

            var reply = SendMessageAndGetReply<GetGameInProgressReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.GameInProgress;
        }

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the GameFocusChangedSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleGameFocusChanged(GameFocusChangedSend message)
        {
            var errorMessage = callbackHandler.ProcessGameFocusChanged(message.GameFocus);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<GameFocusChangedReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the GameInProgressChangedSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleGameInProgressChanged(GameInProgressChangedSend message)
        {
            var errorMessage = callbackHandler.ProcessGameInProgressChanged(message.GameInProgress);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<GameInProgressChangedReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

