//-----------------------------------------------------------------------
// <copyright file = "IAppDecorationManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using Schemas.Internal.AppDecorationTypes;

    /// <summary>
    /// App Decoration Management category of messages.
    /// Category: 131; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IAppDecorationManagementCategory
    {
        /// <summary>
        /// Message from the client to add decorations to apps.
        /// </summary>
        /// <param name="decorationApps">
        /// 
        /// </param>
        void AddDecorationsToApps(IEnumerable<DecorationApps> decorationApps);

        /// <summary>
        /// Message from the client registering a set of decorations.
        /// </summary>
        /// <param name="decorationInfo">
        /// 
        /// </param>
        void RegisterDecorations(IEnumerable<DecorationInfo> decorationInfo);

        /// <summary>
        /// Message from the client to remove decorations from apps.
        /// </summary>
        /// <param name="decorationApps">
        /// 
        /// </param>
        void RemoveDecorationsFromApps(IEnumerable<DecorationApps> decorationApps);

        /// <summary>
        /// Message from the client unregistering a set of decorations.
        /// </summary>
        /// <param name="decorationIds">
        /// 
        /// </param>
        void UnregisterDecorations(IEnumerable<DecorationIdentifier> decorationIds);

    }

}

