//-----------------------------------------------------------------------
// <copyright file = "IBetStepsConfigurationCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.BetStepsConfiguration;

    /// <summary>
    /// BetStepsConfiguration category of messages.  Category: 1011  Version: 1
    /// Category: 1011; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IBetStepsConfigurationCategory
    {
        /// <summary>
        /// Send from Bin to Foundation on the FI channel.  A request for the current bet steps layout style.
        /// </summary>
        /// <returns>
        /// The content of the GetBetStepsConfigurationReply message.
        /// </returns>
        GetBetStepsConfigurationReplyContentBetPresentationStyle GetBetStepsConfiguration();

    }

}

