//-----------------------------------------------------------------------
// <copyright file = "ICertificateManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.CertificateManagement;

    /// <summary>
    /// The CertificateManagement category of messages is to cover a bunch of calls to add and remove certificates from
    /// the certificate store.
    /// Category: 151; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface ICertificateManagementCategory
    {
        /// <summary>
        /// Request to the foundation to add a certificate.
        /// </summary>
        /// <param name="certificateStorageInformation">
        /// Storage Information of the certificate.
        /// </param>
        /// <returns>
        /// The content of the response.  This element should be omitted when an Exception is present.
        /// </returns>
        AddCertificateReplyContent AddCertificate(CertificateInformation certificateStorageInformation);

        /// <summary>
        /// Request to the foundation whether the certificate is installed.
        /// </summary>
        /// <param name="certificateIdentifier">
        /// Certificate identification.
        /// </param>
        /// <returns>
        /// The content of the HasCertificateReply message.
        /// </returns>
        bool HasCertificate(CertificateIdentifier certificateIdentifier);

        /// <summary>
        /// Request to the foundation to remove a certificate.
        /// </summary>
        /// <param name="certificateIdentifier">
        /// Thumbprint for the certificate.
        /// </param>
        /// <returns>
        /// The content of the RemoveCertificateReply message.
        /// </returns>
        Status RemoveCertificate(CertificateIdentifier certificateIdentifier);

    }

}

