//-----------------------------------------------------------------------
// <copyright file = "IClockDisplayCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------
// This file requires manual editing when merging.
// All changes are marked with "MANUAL EDIT:"
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.ClockDisplay;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="ClockDisplay"/> category.
    /// ClockDisplay category of messages.  Category: 127  Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IClockDisplayCategoryCallbacks
    {
        /// <summary>
        /// Notification from Foundation to Bin on the FI channel that the flag to determine if the clock should be
        /// shown has changed.
        /// </summary>
        /// <param name="clockDisplayEnabled">
        /// Flag to determine if the clock should be shown.  True indicates the clock should be shown.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        // MANUAL EDIT: Rename ProcessEnabledChanged to ProcessClockDisplayEnabledChanged.
        string ProcessClockDisplayEnabledChanged(Boolean clockDisplayEnabled);

    }

}

