//-----------------------------------------------------------------------
// <copyright file = "IConfigurationModeControlCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.ConfigurationModeControl;

    /// <summary>
    /// This cateogry provides messages for system level clients to enter and exit the configuration mode.
    /// Category: 138; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IConfigurationModeControlCategory
    {
        /// <summary>
        /// Message from the bin to foundation requesting to enter configuration mode.  B2F: FI channel.
        /// At a time only one client will be allowed to enter configuration mode.
        /// Other contending clients will get a 'Rejected' reply code while one's request is getting processed or is in
        /// configuration mode.
        /// Only system level components, system extensions at this point, are allowed to request entering configuration
        /// mode.
        /// Non system extensions will get an usage error as a reply on request.
        /// </summary>
        /// <param name="forceCashout">
        /// This flag is used by an extension to state if it wants to change configuration with or without credits on
        /// the machine.
        /// If true the player will be forcefully cashed out before entering config mode.
        /// If false the foundation will enter config mode while keeping the player session active as soon it reaches a
        /// 'no game in progress' condition if not in one when the
        /// request was received.
        /// The default value is false for this flag.
        /// </param>
        /// <returns>
        /// The content of the EnterConfigModeRequestReply message.
        /// </returns>
        EnterConfigAcceptanceCode EnterConfigModeRequest(bool forceCashout);

        /// <summary>
        /// Message from the bin to foundation requesting to exit configuration mode.  B2F: FI channel.
        /// </summary>
        void ExitConfigMode();

    }

}

