//-----------------------------------------------------------------------
// <copyright file = "ICoplayerApiControlCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.CoplayerApiControl;
    using Schemas.Internal.Types;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="CoplayerApiControl"/> category.
    /// F2X Coplayer API Control category of messages.
    /// Category: 1013; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface ICoplayerApiControlCategoryCallbacks
    {
        /// <summary>
        /// Message from the Foundation to the Bin on the FI channel to request that the recipient return a list of all
        /// API categories and their versions in the order of preference, specific to the coplayer context.
        /// </summary>
        /// <param name="coplayer">
        /// The coplayer number that API negotiation will support.
        /// </param>
        /// <param name="theme">
        /// Identifies the theme that API negotiation will support.
        /// </param>
        /// <param name="themeTag">
        /// Tag defined by the theme creator - opaque to Foundation.
        /// </param>
        /// <param name="themeTagDataFile">
        /// Tag data file - opaque to Foundation.
        /// </param>
        /// <param name="g2SThemeIdentifier">
        /// Unique G2S theme identifier. This value is defined in the xthemereg registry and must be unique across all
        /// themes in all packages.
        /// </param>
        /// <param name="callbackResult">
        /// [Out] The content of the GetCoplayerApiVersionsReply message.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessGetCoplayerApiVersions(int coplayer, ThemeIdentifier theme, string themeTag, string themeTagDataFile, string g2SThemeIdentifier, out GetCoplayerApiVersionsReplyContentCategoryVersions callbackResult);

        /// <summary>
        /// Message from the Foundation to the Bin on the FI channel to set the API categories and versions the bin is
        /// to support for the coplayer context.
        /// </summary>
        /// <param name="categoryVersions">
        /// The list of categories and their versions.
        /// </param>
        /// <param name="callbackResult">
        /// [Out] The content of the SetCoplayerApiVersionsReply message.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessSetCoplayerApiVersions(SetCoplayerApiVersionsSendCategoryVersions categoryVersions, out bool callbackResult);

    }

}

