//-----------------------------------------------------------------------
// <copyright file = "ICultureWriteCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;

    /// <summary>
    /// CultureWrite category of messages. This category is used by a bin to request changes to the culture.
    /// Category: 140; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface ICultureWriteCategory
    {
        /// <summary>
        /// Message requesting to set the culture.
        /// </summary>
        /// <param name="culture">
        /// The culture to set.
        /// </param>
        void SetCulture(string culture);

        /// <summary>
        /// Message requesting to set the culture to the default. Similar to SetCulture, but does not take a culture
        /// parameter. Simultaneously applies the default Foundation culture and returns the new (default or fallback)
        /// culture.
        /// </summary>
        /// <returns>
        /// The content of the SetDefaultCultureReply message.
        /// </returns>
        string SetDefaultCulture();

    }

}

