//-----------------------------------------------------------------------
// <copyright file = "IFlashPlayerClockCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2022 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.FlashPlayerClock;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="FlashPlayerClock"/> category.
    /// This category contains messages that support (Macau) requirements for flashing the player facing clock under
    /// specific conditions.
    /// Category: 159; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IFlashPlayerClockCategoryCallbacks
    {
        /// <summary>
        /// Notification that one or more of the flash player-clock properties have changed.
        /// </summary>
        /// <param name="flashPlayerClockProperties">
        /// Contains the flash player-clock properties that have changed.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessUpdateFlashPlayerClockProperties(FlashPlayerClockProperties flashPlayerClockProperties);

    }

}

