//-----------------------------------------------------------------------
// <copyright file = "IGameOutcomeEventsCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.GameOutcomeEvents;
    using Schemas.Internal.Types;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="GameOutcomeEvents"/> category.
    /// Game Outcome Events category of messages.  Category: 3018  Version: 1
    /// Category: 3018; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IGameOutcomeEventsCategoryCallbacks
    {
        /// <summary>
        /// Post the final win record.
        /// </summary>
        /// <param name="totalBet">
        /// The total bet amount for this game including any mid-game bets.  The total bet element is always present on
        /// version 1.1 and later.
        /// </param>
        /// <param name="totalWin">
        /// The total win amount excluding WAP wins.
        /// </param>
        /// <param name="paytableWin">
        /// The paytable win amount.
        /// </param>
        /// <param name="progressiveWin">
        /// The progressive win amount excluding WAP wins.
        /// </param>
        /// <param name="ancillaryWin">
        /// The ancillary win amount.
        /// </param>
        /// <param name="externalBonusWin">
        /// The external bonus win amount.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessFinalWinRecordEvent(Amount totalBet, Amount totalWin, Amount paytableWin, Amount progressiveWin, Amount ancillaryWin, Amount externalBonusWin);

    }

}

