//-----------------------------------------------------------------------
// <copyright file = "IGameProgressiveSettingsCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using Schemas.Internal.GameProgressiveSettings;

    /// <summary>
    /// This category provides messages for the game clients to query linked progressive settings during an active theme
    /// context.  Note: The progressive settings do not change during an active theme context.
    /// Category: 1024; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IGameProgressiveSettingsCategory
    {
        /// <summary>
        /// A request for the progressive settings of the linked game levels correlating to the current payvar and
        /// denomination.
        /// </summary>
        /// <returns>
        /// The content of the QueryProgressiveSettingsReply message.
        /// </returns>
        IEnumerable<GameLevelProgressiveSettings> QueryProgressiveSettings();

    }

}

