//-----------------------------------------------------------------------
// <copyright file = "IMachineSupervisionCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{

    /// <summary>
    /// The MachineSupervision category of messages is used to monitor and affect the EGM machine state.
    /// Category: 154; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IMachineSupervisionCategory
    {
        /// <summary>
        /// Request to the foundation to hard reboot the machine.
        /// </summary>
        void RequestMachineReboot();

    }

}

