//-----------------------------------------------------------------------
// <copyright file = "IMidGameMoneyAcceptanceCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;

    /// <summary>
    /// MidGameMoneyAcceptance category of messages.  Provides messages for the game clients to accept money during a
    /// game cycle.
    /// Category: 1025; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IMidGameMoneyAcceptanceCategory
    {
        /// <summary>
        /// End offering mid game money acceptance. Foundation will disable money in during a game cycle.
        /// </summary>
        void EndOfferingMidGameMoneyAcceptance();

        /// <summary>
        /// Request to start offering mid game money acceptance.  Foundation will enable money in during a game cycle if
        /// it's allowed.
        /// </summary>
        /// <returns>
        /// The content of the RequestOfferingMidGameMoneyAcceptanceReply message.
        /// </returns>
        bool RequestOfferingMidGameMoneyAcceptance();

    }

}

