//-----------------------------------------------------------------------
// <copyright file = "INetworkManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using Schemas.Internal.NetworkManagement;

    /// <summary>
    /// The F2X NetworkManagement category of messages assists the client in modifying specific exposed behavior on the
    /// Network Manager.  For example, if a system extension needs to control routing of TCP messages through a NIC,
    /// this category should be used to do so.
    /// Category: 157; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface INetworkManagementCategory
    {
        /// <summary>
        /// Request Foundation to add a new IPv4 routing table entry.
        /// </summary>
        /// <param name="ipv4RoutingTableEntry">
        /// The IPv4 routing table entry infromation to be added.
        /// </param>
        /// <returns>
        /// The content of the AddIpv4RoutingTableEntryReply message.
        /// </returns>
        RoutingTableResult AddIpv4RoutingTableEntry(Ipv4RoutingTableEntry ipv4RoutingTableEntry);

        /// <summary>
        /// Request Foundation to get NIC Information.
        /// </summary>
        /// <returns>
        /// The content of the GetNicInformationReply message.
        /// </returns>
        IEnumerable<NicInformation> GetNicInformation();

    }

}

