//-----------------------------------------------------------------------
// <copyright file = "INicInformationCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.NICInformation;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="NICInformation"/> category.
    /// The NICInformation category of messages to assist the client in determining which NIC IP to bind to. For
    /// example, Windows will sometimes enumerate the video topper NIC first, causing issues when a game uses Windows
    /// API calls directly and winds up binding to the video topper NIC (in which case communications will never work).
    /// Category: 142; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface INicInformationCategoryCallbacks
    {
        /// <summary>
        /// Notification that the network settings have changed. This notification gets sent up when the foundation's
        /// config item (that stores the current IP for the NIC) is updated with a new IP address.
        /// </summary>
        /// <param name="content">
        /// 
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessNetworkSettingsChanged(PrioritizedIPList content);

    }

}

