//-----------------------------------------------------------------------
// <copyright file = "IPidSessionTrackingCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.PIDSessionTracking;

    /// <summary>
    /// PIDSessionTracking category. Defines messages to handle the PID (Player Information Display) session tracking
    /// information which is displayed by games on the screen.
    /// Category: 1039; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IPidSessionTrackingCategory
    {
        /// <summary>
        /// Get the PID session data that is tracked.
        /// </summary>
        /// <returns>
        /// The content of the GetSessionDataReply message.
        /// </returns>
        SessionData GetSessionData();

        /// <summary>
        /// Client notifies the Foundation that a PID tracking session is started.
        /// </summary>
        void StartTracking();

        /// <summary>
        /// Client notifies the Foundation that a PID tracking session is stopped.
        /// </summary>
        void StopTracking();

    }

}

