//-----------------------------------------------------------------------
// <copyright file = "IPlayerTippingCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.PlayerTipping;
    using Schemas.Internal.Types;

    /// <summary>
    /// PlayerTipping category.  Defines messages between extensions and foundation to satisfy printing of tipping
    /// vouchers.
    /// Category: 3032; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IPlayerTippingCategory
    {
        /// <summary>
        /// Retrieves the player tipping related properties. All properties will be returned in this message. This
        /// message may **ONLY** be sent during context activation.
        /// </summary>
        /// <returns>
        /// The content of the GetPropertiesReply message.
        /// </returns>
        Properties GetProperties();

        /// <summary>
        /// Request from extension to get cashout ticket data.
        /// </summary>
        /// <param name="amount">
        /// The amount of the cashout ticket to be printed.
        /// </param>
        /// <returns>
        /// The content of the TippingRequestReply message.
        /// </returns>
        bool TippingRequest(Amount amount);

    }

}

