//-----------------------------------------------------------------------
// <copyright file = "IReportGamePerformanceCategoryCallbacks.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using Schemas.Internal.ReportGamePerformance;
    using Schemas.Internal.Types;

    /// <summary>
    /// Interface that handles callbacks from the F2X <see cref="ReportGamePerformance"/> category.
    /// Report Game Performance category of messages.  Category: 4003  Version: 1. This category is used to request game
    /// specific performance data.
    /// The data payload can be any well formed xml with an entirely game-defined schema, and is stored together with
    /// the GamePerformanceData.xml
    /// export.
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IReportGamePerformanceCategoryCallbacks
    {
        /// <summary>
        /// Request from the Foundation for a game performance report.
        /// </summary>
        /// <param name="theme">
        /// Identifies the theme to use for generating the report.
        /// </param>
        /// <param name="payvar">
        /// Identifies the payvar to use for generating the report.
        /// </param>
        /// <param name="callbackResult">
        /// [Out] The game performance report data that was requested.
        /// </param>
        /// <returns>
        /// An error message if an error occurs; otherwise, null.
        /// </returns>
        string ProcessGetPerformanceReport(ThemeIdentifier theme, PayvarIdentifier payvar, out GetPerformanceReportReplyContent callbackResult);

    }

}

