//-----------------------------------------------------------------------
// <copyright file = "ISessionManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using Schemas.Internal.SessionManagement;

    /// <summary>
    /// F2X Session Management category of messages.
    /// Category: 1016; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface ISessionManagementCategory
    {
        /// <summary>
        /// Message from the Bin to the Foundation on the FI channel for requesting to create a new session.
        /// </summary>
        /// <returns>
        /// The content of the response.  This element should be omitted when an Exception is present.
        /// </returns>
        CreateSessionReplyContent CreateSession();

        /// <summary>
        /// Message from the Bin to the Foundation on the FI channel for requesting to destroy the specified session.
        /// </summary>
        /// <param name="session">
        /// The session number to be destroyed.
        /// </param>
        void DestroySession(int session);

        /// <summary>
        /// Message from the Bin to the Foundation on the FI channel for requesting to launch the specified session.
        /// </summary>
        /// <param name="session">
        /// The session number to be launched.
        /// </param>
        void LaunchSession(int session);

    }

}

