//-----------------------------------------------------------------------
// <copyright file = "IShellStoreCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    /// <summary>
    /// F2X Shell Store category of messages, which provides the APIs for the concurrent game shell to access its
    /// critical data.
    /// Category: 1019; Major Version: 1
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface IShellStoreCategory : IKeyValueStoreCategory
    {
    }

}

