//-----------------------------------------------------------------------
// <copyright file = "ITransactionalCritDataWriteCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using Schemas.Internal.TransactionalCritDataWrite;

    /// <summary>
    /// Transactional Critical Data Write category of messages.  Category: 123  Version: 1.
    /// </summary>
    /// <remarks>
    /// All documentation is generated from the XSD schema files.
    /// </remarks>
    public interface ITransactionalCritDataWriteCategory
    {
        /// <summary>
        /// Message from the bin to the foundation requesting to remove critical data with the given scope and name.
        /// </summary>
        /// <param name="criticalDataItems">
        /// A collection of crtiical data items to be removed. / A critical data item to be removed.
        /// </param>
        void RemoveCritData(IEnumerable<CriticalDataItemSelector> criticalDataItems);

        /// <summary>
        /// Sent from the bin to the foundation on the FI channel. A request to write critical data.
        /// </summary>
        /// <param name="writeCritDataContent">
        /// The critical data items that are to be written.
        /// </param>
        void WriteCritData(WriteCritDataSendContent writeCritDataContent);

    }

}

