//-----------------------------------------------------------------------
// <copyright file = "PlayerInformationDisplayCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.PlayerInformationDisplay;

    /// <summary>
    /// Implementation of the F2X <see cref="PlayerInformationDisplay"/> category.
    /// PlayerInformationDisplay category. Defines messages to synchronize the PID game information which is displayed
    /// on the screen.
    /// Category: 1038; Major Version: 1
    /// </summary>
    public class PlayerInformationDisplayCategory : F2XTransactionalCategoryBase<PlayerInformationDisplay>, IPlayerInformationDisplayCategory
    {
        #region Fields

        /// <summary>
        /// Object which implements the PlayerInformationDisplayCategory callbacks.
        /// </summary>
        private readonly IPlayerInformationDisplayCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="PlayerInformationDisplayCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// PlayerInformationDisplayCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public PlayerInformationDisplayCategory(IF2XTransport transport, IPlayerInformationDisplayCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<PidConfigurationChangedSend>(HandlePidConfigurationChanged);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.PlayerInformationDisplay;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IPlayerInformationDisplayCategory Members

        /// <inheritdoc/>
        public void ActivationStatusChanged(bool isActive)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<ActivationStatusChangedSend>();
            var content = (ActivationStatusChangedSend)request.Message.Item;
            content.IsActive = isActive;

            var reply = SendMessageAndGetReply<ActivationStatusChangedReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        /// <inheritdoc/>
        public void GameInformationScreenEntered()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GameInformationScreenEnteredSend>();

            var reply = SendMessageAndGetReply<GameInformationScreenEnteredReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        /// <inheritdoc/>
        public PidConfigurationInfo GetPidConfiguration()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<GetPidConfigurationSend>();

            var reply = SendMessageAndGetReply<GetPidConfigurationReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content.PidConfigurationInfo;
        }

        /// <inheritdoc/>
        public void SessionInformationScreenEntered()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<SessionInformationScreenEnteredSend>();

            var reply = SendMessageAndGetReply<SessionInformationScreenEnteredReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the PidConfigurationChangedSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandlePidConfigurationChanged(PidConfigurationChangedSend message)
        {
            var errorMessage = callbackHandler.ProcessPidConfigurationChanged(message.PidConfigurationInfo);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<PidConfigurationChangedReply>(errorCode, errorMessage);
            SendFoundationNonTransactionalChannelResponse(replyMessage);
        }

        #endregion

    }

}

