//-----------------------------------------------------------------------
// <copyright file = "PlayerControlContextMonitoringCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.PlayerControlContextMonitoring;

    /// <summary>
    /// Implementation of the F2X <see cref="PlayerControlContextMonitoring"/> category.
    /// The PlayerControlContextMonitoring category of messages allows the client to monitor the state of the
    /// Foundation's player control context.  This is useful for ContinuousSystemActivation extensions, which otherwise
    /// have no mechanism to observe the context.
    /// Category: 145; Major Version: 1
    /// </summary>
    public class PlayerControlContextMonitoringCategory : F2XCategoryBase<PlayerControlContextMonitoring>
    {
        #region Fields

        /// <summary>
        /// Object which implements the PlayerControlContextMonitoringCategory callbacks.
        /// </summary>
        private readonly IPlayerControlContextMonitoringCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="PlayerControlContextMonitoringCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// PlayerControlContextMonitoringCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public PlayerControlContextMonitoringCategory(IF2XTransport transport, IPlayerControlContextMonitoringCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<PlayerControlContextStateUpdateSend>(HandlePlayerControlContextStateUpdate);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.PlayerControlContextMonitoring;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the PlayerControlContextStateUpdateSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandlePlayerControlContextStateUpdate(PlayerControlContextStateUpdateSend message)
        {
            var errorMessage = callbackHandler.ProcessPlayerControlContextStateUpdate(message.PlayerControlContextState);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<PlayerControlContextStateUpdateReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

