//-----------------------------------------------------------------------
// <copyright file = "RetrieveGameLevelAwardsCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System.Collections.Generic;
    using System.Linq;
    using F2XTransport;
    using Schemas.Internal.RetrieveGameLevelAwards;
    using Schemas.Internal.Types;

    /// <summary>
    /// Implementation of the F2X <see cref="RetrieveGameLevelAwards"/> category.
    /// Category of messages.  Category: 115 Version: 1. This category is used to retrieve (progressive) game level
    /// award information.
    /// </summary>
    public class RetrieveGameLevelAwardsCategory : F2XCategoryBase<RetrieveGameLevelAwards>, IRetrieveGameLevelAwardsCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="RetrieveGameLevelAwardsCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public RetrieveGameLevelAwardsCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.RetrieveGameLevelAwards;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region IRetrieveGameLevelAwardsCategory Members

        /// <inheritdoc/>
        public IEnumerable<GameLevelThemeData> GetGameLevelAwardValues(IEnumerable<ThemeIdentifier> theme)
        {
            var request = CreateBasicRequest<GetGameLevelAwardValuesSend>();
            var content = (GetGameLevelAwardValuesSend)request.Message.Item;
            content.Theme = theme == null ? null : theme.ToList();

            var reply = SendMessageAndGetReply<GetGameLevelAwardValuesReply>(Channel.Game, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        #endregion

    }

}

