//-----------------------------------------------------------------------
// <copyright file = "SessionManagementCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.SessionManagement;

    /// <summary>
    /// Implementation of the F2X <see cref="SessionManagement"/> category.
    /// F2X Session Management category of messages.
    /// Category: 1016; Major Version: 1
    /// </summary>
    public class SessionManagementCategory : F2XTransactionalCategoryBase<SessionManagement>, ISessionManagementCategory
    {
        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="SessionManagementCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        public SessionManagementCategory(IF2XTransport transport)
            : base(transport)
        {
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.SessionManagement;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region ISessionManagementCategory Members

        /// <inheritdoc/>
        public CreateSessionReplyContent CreateSession()
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<CreateSessionSend>();

            var reply = SendMessageAndGetReply<CreateSessionReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
            return reply.Content;
        }

        /// <inheritdoc/>
        public void DestroySession(int session)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<DestroySessionSend>();
            var content = (DestroySessionSend)request.Message.Item;
            content.Session = session;

            var reply = SendMessageAndGetReply<DestroySessionReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        /// <inheritdoc/>
        public void LaunchSession(int session)
        {
            Transport.MustHaveHeavyweightTransaction();
            var request = CreateTransactionalRequest<LaunchSessionSend>();
            var content = (LaunchSessionSend)request.Message.Item;
            content.Session = session;

            var reply = SendMessageAndGetReply<LaunchSessionReply>(Channel.Foundation, request);
            CheckReply(reply.Exception);
        }

        #endregion

    }

}

