//-----------------------------------------------------------------------
// <copyright file = "ShellActivationCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.ShellActivation;

    /// <summary>
    /// Implementation of the F2X <see cref="ShellActivation"/> category.
    /// F2X Shell Activation category of messages.
    /// Category: 1010; Major Version: 1
    /// </summary>
    public class ShellActivationCategory : F2XCategoryBase<ShellActivation>
    {
        #region Fields

        /// <summary>
        /// Object which implements the ShellActivationCategory callbacks.
        /// </summary>
        private readonly IShellActivationCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="ShellActivationCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// ShellActivationCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public ShellActivationCategory(IF2XTransport transport, IShellActivationCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<ActivateShellContextSend>(HandleActivateShellContext);
            AddMessagehandler<InactivateShellContextSend>(HandleInactivateShellContext);
            AddMessagehandler<NewShellContextSend>(HandleNewShellContext);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.ShellActivation;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the ActivateShellContextSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleActivateShellContext(ActivateShellContextSend message)
        {
            var errorMessage = callbackHandler.ProcessActivateShellContext();
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<ActivateShellContextReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the InactivateShellContextSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleInactivateShellContext(InactivateShellContextSend message)
        {
            var errorMessage = callbackHandler.ProcessInactivateShellContext();
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<InactivateShellContextReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the NewShellContextSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleNewShellContext(NewShellContextSend message)
        {
            var errorMessage = callbackHandler.ProcessNewShellContext(message.GameMode, message.SecurityLevel);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<NewShellContextReply>(errorCode, errorMessage);
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

