//-----------------------------------------------------------------------
// <copyright file = "ShellApiControlCategory.cs" company = "IGT">
//     Copyright (c) 2020 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by C3G.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2X
{
    using System;
    using F2XTransport;
    using Schemas.Internal.ShellApiControl;

    /// <summary>
    /// Implementation of the F2X <see cref="ShellApiControl"/> category.
    /// F2X Shell API Control category of messages.
    /// Category: 1009; Major Version: 1
    /// </summary>
    public class ShellApiControlCategory : F2XCategoryBase<ShellApiControl>
    {
        #region Fields

        /// <summary>
        /// Object which implements the ShellApiControlCategory callbacks.
        /// </summary>
        private readonly IShellApiControlCategoryCallbacks callbackHandler;

        #endregion

        #region Constructor

        /// <summary>
        /// Instantiates a new <see cref="ShellApiControlCategory"/>.
        /// </summary>
        /// <param name="transport">
        /// Transport that this category will be installed in.
        /// </param>
        /// <param name="callbackHandler">
        /// ShellApiControlCategory callback handler.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="callbackHandler"/> is null.
        /// </exception>
        public ShellApiControlCategory(IF2XTransport transport, IShellApiControlCategoryCallbacks callbackHandler)
            : base(transport)
        {
            this.callbackHandler = callbackHandler ?? throw new ArgumentNullException(nameof(callbackHandler));
            AddMessagehandler<GetShellApiVersionsSend>(HandleGetShellApiVersions);
            AddMessagehandler<SetShellApiVersionsSend>(HandleSetShellApiVersions);
        }

        #endregion

        #region IApiCategory Members

        /// <inheritdoc/>
        public override MessageCategory Category => MessageCategory.ShellApiControl;

        /// <inheritdoc/>
        public override uint MajorVersion => 1;

        /// <inheritdoc/>
        public override uint MinorVersion => 0;

        #endregion

        #region Message Handlers

        /// <summary>
        /// Handler for the GetShellApiVersionsSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleGetShellApiVersions(GetShellApiVersionsSend message)
        {
            GetShellApiVersionsReplyContentCategoryVersions callbackResult;
            var errorMessage = callbackHandler.ProcessGetShellApiVersions(message.Shell, message.TagDataFile, message.LinkedExtensions, out callbackResult);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<GetShellApiVersionsReply>(errorCode, errorMessage);
            var reply = (GetShellApiVersionsReply)replyMessage.Message.Item;
            reply.Content.CategoryVersions = callbackResult;
            SendFoundationChannelResponse(replyMessage);
        }

        /// <summary>
        /// Handler for the SetShellApiVersionsSend message.
        /// </summary>
        /// <param name="message">
        /// Message from the Foundation to handle.
        /// </param>
        private void HandleSetShellApiVersions(SetShellApiVersionsSend message)
        {
            bool callbackResult;
            var errorMessage = callbackHandler.ProcessSetShellApiVersions(message.CategoryVersions, out callbackResult);
            var errorCode = string.IsNullOrEmpty(errorMessage) ? 0 : 1;
            var replyMessage = CreateReply<SetShellApiVersionsReply>(errorCode, errorMessage);
            var reply = (SetShellApiVersionsReply)replyMessage.Message.Item;
            reply.Content.CategoriesAccepted = callbackResult;
            SendFoundationChannelResponse(replyMessage);
        }

        #endregion

    }

}

