//-----------------------------------------------------------------------
// <copyright file = "IBetModifierResult.cs" company = "IGT">
//     Copyright (c) 2014 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Logic.BetFramework.Interfaces
{
    /// <summary>
    /// The validated result of executing a bet modifier.
    /// </summary>
    public interface IBetModifierResult
    {
        /// <summary>
        /// Name of the modifier which generated <see cref="Data"/>.
        /// </summary>
        string ModifierName { get; }

        /// <summary>
        /// Flag indicating whether <see cref="Data"/> is valid.
        /// </summary>
        bool Valid { get; }

        /// <summary>
        /// The <see cref="IBetData"/> generated by <see cref="ModifierName"/>.
        /// </summary>
        IBetData Data { get; }
    }
}