//-----------------------------------------------------------------------
// <copyright file = "MessageCategory.cs" company = "IGT">
//     Copyright (c) 2011 IGT.  All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace IGT.Game.Core.Communication.Foundation.F2XTransport
{
    /// <summary>
    /// Enumeration containing F2X message Categories. These values should be defined in the appropriate schemas 
    /// for each category, and mirrored here: https://developers.confluence.igt.com/display/AF/F2X+Categories.
    /// Note that usually these enums are generated by the C3G tool and manually copy/pasted to this file.
    /// </summary>
    public enum MessageCategory : uint
    {
        #region F2L message category

        /// <summary>
        /// Represents the Connect category.
        /// </summary>
        F2LConnect = 1,

        /// <summary>
        /// Represents the LinkControl category.
        /// </summary>
        F2LLinkControl = 2,

        /// <summary>
        /// Represents the GameControl category.
        /// </summary>
        GameControl = 3,

        /// <summary>
        /// Represents the ShowDemo category.
        /// </summary>
        Show = 4,

        /// <summary>
        /// Represents the GameStopReport category.
        /// </summary>
        GameStopReport = 5,

        /// <summary>
        /// Represents the Identification category.
        /// </summary>
        Identification = 6,

        /// <summary>
        /// Represents the GameTilt category.
        /// </summary>
        GameTilt = 7,

        /// <summary>
        /// Represents the AutoPlay category.
        /// </summary>
        AutoPlay = 8,

        /// <summary>
        /// Represents the GameContextLocking category.
        /// </summary>
        GameContextLocking = 9,

        /// <summary>
        /// Represents the VoucherPrint category.
        /// </summary>
        VoucherPrint = 10,

        /// <summary>
        /// Represents the ProtocolIPPForwarding category.
        /// </summary>
        ProtocolIppForwarding = 11,

        /// <summary>
        /// Represents the CdsItaly category.
        /// </summary>
        CdsItaly = 12,

        /// <summary>
        /// Represents the CdsItalyMockEnrollment category.
        /// </summary>
        CdsItalyMockEnrollment = 13,

        /// <summary>
        /// Represents the ThemeToExtParcelComm category.
        /// </summary>
        ThemeToExtParcelComm = 14,

        /// <summary>
        /// Represents the ForceGameCompletion category.
        /// </summary>
        ForceGameCompletion = 15,

        #endregion

        #region UGP specific message category

        /// <summary>
        /// UGP specific progressive award category.
        /// </summary>
        UgpProgressiveAward = 20,

        /// <summary>
        /// UGP specific PID category.
        /// </summary>
        UgpPid = 21,

        /// <summary>
        /// UGP specific game meter category.
        /// </summary>
        UgpGameMeter = 22,

        /// <summary>
        /// UGP specific message strip category.
        /// </summary>
        UgpMessageStrip = 23,

        /// <summary>
        /// UGP specific reserve category.
        /// </summary>
        UgpReserve = 24,

        /// <summary>
        /// UGP specific runtime game event category.
        /// </summary>
        UgpRunTimeGameEvent = 25,

        /// <summary>
        /// UGP specific machine configuration category.
        /// </summary>
        UgpMachineConfiguration = 26,

        /// <summary>
        /// UGP specific external jackpots category.
        /// </summary>
        UgpExternalJackpots = 27,

        /// <summary>
        /// UGP specific random number category.
        /// </summary>
        UgpRandomNumber = 28,

        /// <summary>
        /// UGP specific progressive category.
        /// </summary>
        UgpProgressive = 29,

        #endregion

        #region UC specific message category

        /// <summary>
        /// Represents the WapSignControl category.
        /// </summary>
        WapSignControl = 30,

        #endregion

        #region F2X message category

        /// <summary>
        /// Represents the Connect category.
        /// </summary>
        F2XConnect = 101,

        /// <summary>
        /// Represents the LinkControl category.
        /// </summary>
        F2XLinkControl = 102,

        /// <summary>
        /// Represents the TransactionComplete category.
        /// </summary>
        TransactionComplete = 103,

        /// <summary>
        /// Represents the ActionRequest category.
        /// </summary>
        ActionRequest = 104,

        /// <summary>
        /// Represents the Activation category.
        /// </summary>
        Activation = 105,

        /// <summary>
        /// Represents the ProgressiveData category.
        /// </summary>
        ProgressiveData = 106,

        /// <summary>
        /// Represents the CustomConfigurationRead category.
        /// </summary>
        CustomConfigurationRead = 107,

        /// <summary>
        /// Represents the GameInformation category.
        /// </summary>
        GameInformation = 108,

        /// <summary>
        /// Represents the Localization category.
        /// </summary>
        Localization = 109,

        /// <summary>
        /// Represents the EGMConfigData category.
        /// </summary>
        EgmConfigData = 110,

        /// <summary>
        /// Represents the DateTime category.
        /// </summary>
        DateTime = 111,

        /// <summary>
        /// Represents the GameLink category.
        /// </summary>
        GameLink = 112,

        /// <summary>
        /// Represents the TournamentMeters category.
        /// </summary>
        TournamentMeters = 113,

        /// <summary>
        /// Represents the PlayerSession category.
        /// </summary>
        PlayerSession = 114,

        /// <summary>
        /// Represents the RetrieveGameLevelAwards category.
        /// </summary>
        RetrieveGameLevelAwards = 115,

        /// <summary>
        /// Represents the NonTransactionalCritDataRead category.
        /// </summary>
        NonTransactionalCritDataRead = 116,

        /// <summary>
        /// Represents the ThemedHandpay category.
        /// </summary>
        ThemedHandpay = 118,

        /// <summary>
        /// Represents the CultureRead category.
        /// </summary>
        CultureRead = 119,

        /// <summary>
        /// Represents the JackpotItaly category.
        /// </summary>
        JackpotItaly = 120,

        /// <summary>
        /// Represents the TransactionalCritDataRead category.
        /// </summary>
        TransactionalCritDataRead = 121,

        /// <summary>
        /// Represents the GameGroupInformation category.
        /// </summary>
        GameGroupInformation = 122,

        /// <summary>
        /// Represents the TransactionalCritDataWrite category.
        /// </summary>
        TransactionalCritDataWrite = 123,

        /// <summary>
        /// Represents the PlayerSessionParameters category.
        /// </summary>
        PlayerSessionParameters = 124,

        /// <summary>
        /// Represents the TiltControl category.
        /// </summary>
        TiltControl = 126,

        /// <summary>
        /// Represents the MachineIdentification category.
        /// </summary>
        MachineIdentification = 125,

        /// <summary>
        /// Represents the ClockDisplay category.
        /// </summary>
        ClockDisplay = 127,

        /// <summary>
        /// Represents the ParcelComm category.
        /// </summary>
        ParcelComm = 128,

        /// <summary>
        /// Represents the AppQuery category.
        /// </summary>
        AppQuery = 129,

        /// <summary>
        /// Represents the DisplayControl category.
        /// </summary>
        DisplayControl = 130,

        /// <summary>
        /// Represents the AppDecorationManagement category.
        /// </summary>
        AppDecorationManagement = 131,

        /// <summary>
        /// Represents the AppDecorationQuery category.
        /// </summary>
        AppDecorationQuery = 132,

        /// <summary>
        /// Represents the BankStatus category.
        /// </summary>
        BankStatus = 133,

        /// <summary>
        /// Represents the CashDeviceSupervision category.
        /// </summary>
        CashDeviceSupervision = 134,

        /// <summary>
        /// Represents the TicketPrintControl category.
        /// </summary>
        TicketPrintControl = 135,

        /// <summary>
        /// Represents the FirewallManager category.
        /// </summary>
        FirewallManager = 136,

        /// <summary>
        /// Represents the AppStorage category.
        /// </summary>
        AppStorage = 137,

        /// <summary>
        /// Represents the ConfigurationModeControl category.
        /// </summary>
        ConfigurationModeControl = 138,

        /// <summary>
        /// Represents the ConfigurationModeMonitoring category.
        /// </summary>
        ConfigurationModeMonitoring = 139,

        /// <summary>
        /// Represents the CultureWrite category.
        /// </summary>
        CultureWrite = 140,

        /// <summary>
        /// Represents the EventBasedProgressive category.
        /// </summary>
        EventBasedProgressive = 141,

        /// <summary>
        /// Represents the NICInformation category.
        /// </summary>
        NicInformation = 142,

        /// <summary>
        /// Represents the EventLog category.
        /// </summary>
        EventLog = 143,

        /// <summary>
        /// Represents the SportsBettingGamingCycle category.
        /// </summary>
        SportsBettingGamingCycle = 144,

        /// <summary>
        /// Represents the PlayerControlContextMonitoring category.
        /// </summary>
        PlayerControlContextMonitoring = 145,

        /// <summary>
        /// Represents the Cashout category.
        /// </summary>
        Cashout = 146,

        /// <summary>
        /// Represents the CallAttendant category.
        /// </summary>
        CallAttendant = 149,

        /// <summary>
        /// Represents the VoucherRedemption category.
        /// </summary>
        VoucherRedemption = 150,

        /// <summary>
        /// Represents the CertificateManagement category.
        /// </summary>
        CertificateManagement = 151,

        /// <summary>
        /// Represents the MessageStrip category.
        /// </summary>
        MessageStrip = 152,

        /// <summary>
        /// Represents the MachineSupervision category.
        /// </summary>
        MachineSupervision = 154,

        /// <summary>
        /// Represents the RuntimeGameEvents category.
        /// </summary>
        RuntimeGameEvents = 155,

        /// <summary>
        /// Represents the ChooserServices category.
        /// </summary>
        ChooserServices = 156,

        /// <summary>
        /// Represents the NetworkManagement category.
        /// </summary>
        NetworkManagement = 157,

        /// <summary>
        /// Represents the PerformCashout category.
        /// </summary>
        PerformCashout = 158,
        
        /// <summary>
        /// Represents the FlashPlayerClock category.
        /// </summary>
        FlashPlayerClock = 159,

        /// <summary>
        /// Represents the G2SConnection category.
        /// </summary>
        G2SConnection = 160,

        /// <summary>
        /// Represents the TournamentSessionControl category.
        /// </summary>
        TournamentSessionControl = 1001,

        /// <summary>
        /// Represents the category for the CDS Pull Tab protocol.
        /// </summary>
        CdsPullTab = 1002,

        /// <summary>
        /// Represents the GameGroupControl category.
        /// </summary>
        GameGroupControl = 1003,

        /// <summary>
        /// Represents the LegacyBonusControl category.
        /// </summary>
        LegacyBonusControl = 1004,

        /// <summary>
        /// Represents the GamePlayReporting category.
        /// </summary>
        GamePlayReporting = 1005,

        /// <summary>
        /// Represents the ThemeControl category.
        /// </summary>
        ThemeControl = 1006,

        /// <summary>
        /// Represents the CdsIcd category.
        /// </summary>
        CdsIcd = 1007,

        /// <summary>
        /// Represents the AppControlClient category.
        /// </summary>
        AppControlClient = 1008,

        /// <summary>
        /// Represents the ShellApiControl category.
        /// </summary>
        ShellApiControl = 1009,

        /// <summary>
        /// Represents the ShellActivation category.
        /// </summary>
        ShellActivation = 1010,

        /// <summary>
        /// Represents the BetStepsConfiguration category.
        /// </summary>
        BetStepsConfiguration = 1011,

        /// <summary>
        /// Represents the CoplayerManagement category.
        /// </summary>
        CoplayerManagement = 1012,
     
        /// <summary>
        /// Represents the CoplayerApiControl category.
        /// </summary>
        CoplayerApiControl = 1013,
     
        /// <summary>
        /// Represents the CoplayerActivation category.
        /// </summary>
        CoplayerActivation = 1014,
     
        /// <summary>
        /// Represents the ShellThemeControl category.
        /// </summary>
        ShellThemeControl = 1015,
     
        /// <summary>
        /// Represents the SessionManagement category.
        /// </summary>
        SessionManagement = 1016,

        /// <summary>
        /// Represents the GameCycleBetting category.
        /// </summary>
        GameCycleBetting = 1017,

        /// <summary>
        /// Represents the RandomNumberGeneration category.
        /// </summary>
        RandomNumberGeneration = 1018,

        /// <summary>
        /// Represents the ShellStore category.
        /// </summary>
        ShellStore = 1019,

        /// <summary>
        /// Represents the GameCyclePlay category.
        /// </summary>
        GameCyclePlay = 1020,

        /// <summary>
        /// Represents the ThemeStore category.
        /// </summary>
        ThemeStore = 1021,

        /// <summary>
        /// Represents the PayvarStore category.
        /// </summary>
        PayvarStore = 1022,

        /// <summary>
        /// Represents the GameProgressiveSettings category.
        /// </summary>
        GameProgressiveSettings = 1024,

        /// <summary>
        /// Represents the MidGameMoneyAcceptance category.
        /// </summary>
        MidGameMoneyAcceptance = 1025,

        /// <summary>
        /// Represents the CoplayerHistoryStore category.
        /// </summary>
        CoplayerHistoryStore = 1026,

        /// <summary>
        /// Represents the ShellHistoryStore category.
        /// </summary>
        ShellHistoryStore = 1027,

        /// <summary>
        /// Represents the ActionRequestLite category.
        /// </summary>
        ActionRequestLite = 1028,

        /// <summary>
        /// Represents the BankPlay category.
        /// </summary>
        BankPlay = 1029,

        /// <summary>
        /// Represents the GamePlayStore category.
        /// </summary>
        GamePlayStore = 1030,

        /// <summary>
        /// Represents the ShowDemo category.
        /// </summary>
        ShowDemo = 1031,

        /// <summary>
        /// Represents the GamePlayStatus category.
        /// </summary>
        GamePlayStatus = 1032,

        /// <summary>
        /// Represents the GamePresentationBehavior category.
        /// </summary>
        GamePresentationBehavior = 1033,

        /// <summary>
        /// Represents the ShellHistoryControl category.
        /// </summary>
        ShellHistoryControl = 1034,

        /// <summary>
        /// Represents the CdsHhr category.
        /// </summary>
        CdsHhr = 1035,

        /// <summary>
        /// Represents the GameReserve category.
        /// </summary>
        GameReserve = 1036,

        /// <summary>
        /// Represents the CdsEcp category.
        /// </summary>
        CdsEcp = 1037,

        /// <summary>
        /// Represents the PlayerInformationDisplay category.
        /// </summary>
        PlayerInformationDisplay = 1038,

        /// <summary>
        /// Represents the PIDSessionTracking category.
        /// </summary>
        PidSessionTracking = 1039,

        /// <summary>
        /// Represents the GameHistorySupplemental category.
        /// </summary>
        GameHistorySupplemental = 1040,

        /// <summary>
        /// Represents the AppControl category.
        /// </summary>
        AppControl = 2000,

        /// <summary>
        /// Represents the ChooserDefinitionQuery category.
        /// </summary>
        ChooserDefinitionQuery = 2001,
        
        /// <summary>
        /// Represents the SelectionManagement category.
        /// </summary>
        SelectionManagement = 2002,

        /// <summary>
        /// Represents the ThemeApiControl category.
        /// </summary>
        ThemeApiControl = 3001,

        /// <summary>
        /// Represents the ThemeActivation category.
        /// </summary>
        ThemeActivation = 3002,

        /// <summary>
        /// Represents the TsmApiControl category.
        /// </summary>
        TsmApiControl = 3003,

        /// <summary>
        /// Represents the TsmActivation category.
        /// </summary>
        TsmActivation = 3004,

        /// <summary>
        /// Represents the CdsBingo category.
        /// </summary>
        CdsBingo = 3009,

        /// <summary>
        /// Represents the CdsBingoConfig category.
        /// </summary>
        CdsBingoConfig = 3010,

        /// <summary>
        /// Represents the SystemApiControl category.
        /// </summary>
        SystemApiControl = 3011,

        /// <summary>
        /// Represents the SystemActivation category.
        /// </summary>
        SystemActivation = 3012,

        /// <summary>
        /// Represents the CdsBingoMeterReader category.
        /// </summary>
        CdsBingoMeterReader = 3013,

        /// <summary>
        /// Represents the Bonusing category.
        /// </summary>
        Bonusing = 3014,

        /// <summary>
        /// Represents the ThemeDisplayEvents category.
        /// </summary>
        ThemeDisplayEvents = 3015,

        /// <summary>
        /// Represents the GameCycleSupervision category.
        /// </summary>
        GameCycleSupervision = 3016,

        /// <summary>
        /// Represents the GameCycleEvents category.
        /// </summary>
        GameCycleEvents = 3017,

        /// <summary>
        /// Represents the GameOutcomeEvents category.
        /// </summary>
        GameOutcomeEvents = 3018,

        /// <summary>
        /// Represents the VKBingo category.
        /// </summary>
        VkBingo = 3020,

        /// <summary>
        /// Represents the WinMismatch category.
        /// </summary>
        WinMismatch = 3022,

        /// <summary>
        /// Represents the ExtensionProgressiveControllerConfig category.
        /// </summary>
        ExtensionProgressiveControllerConfig = 3023,

        /// <summary>
        /// Represents the ExtensionProgressiveControllerRuntime category.
        /// </summary>
        ExtensionProgressiveControllerRuntime = 3024,

        /// <summary>
        /// Represents the ExtensionProgressiveControllerLinking category.
        /// </summary>
        ExtensionProgressiveControllerLinking = 3025,

        /// <summary>
        /// Represents the AscribedShellActivation category.
        /// </summary>
        AscribedShellActivation = 3026,

        /// <summary>
        /// Represents the AscribedGameApiControl category.
        /// </summary>
        AscribedGameApiControl = 3027,

        /// <summary>
        /// Represents the ResponsibleGamingSessionDisplay category.
        /// </summary>
        ResponsibleGamingSessionDisplay = 3028,

        /// <summary>
        /// Represents the AppApiControl category.
        /// </summary>
        AppApiControl = 3030,

        /// <summary>
        /// Represents the AppActivation category.
        /// </summary>
        AppActivation = 3031,

        /// <summary>
        /// Represents the PlayerTipping category.
        /// </summary>
        PlayerTipping = 3032,

        /// <summary>
        /// Represents the ExtensionAppSelection category.
        /// </summary>
        ExtensionAppSelection = 3033,

        /// <summary>
        /// Represents the PlayerCardServices category.
        /// </summary>
        PlayerCardServices = 3035,

        /// <summary>
        /// Represents the DftMeterReader category.
        /// </summary>
        DftMeterReader = 3036,

        /// <summary>
        /// Represents the EbpConfiguration category.
        /// </summary>
        EbpConfiguration = 3037,

        /// <summary>
        /// Represents the ReportGameDataInspection category.
        /// </summary>
        ReportGameDataInspection = 4001,

        /// <summary>
        /// Represents the GameLevelAward category.
        /// </summary>
        GameLevelAward = 4002,

        /// <summary>
        /// Represents the ReportGamePerformance category.
        /// </summary>
        ReportGamePerformance = 4003,

        /// <summary>
        /// Represents the SetupValidation category.
        /// </summary>
        SetupValidation = 4004,

        #endregion
    }
}
