//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace IGT.Game.Core.ToolSupport.Schemas.SystemRequirements.Ver1 {
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SystemRequirements {
        
        private Storage storageField;
        
        private Hardware hardwareField;
        
        private uint versionField;
        
        /// <remarks/>
        public Storage Storage {
            get {
                return this.storageField;
            }
            set {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        public Hardware Hardware {
            get {
                return this.hardwareField;
            }
            set {
                this.hardwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Storage {
        
        private long ramField;
        
        private int nvramField;
        
        private bool nvramFieldSpecified;
        
        public Storage() {
            this.ramField = ((long)(4));
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "4")]
        public long Ram {
            get {
                return this.ramField;
            }
            set {
                this.ramField = value;
            }
        }
        
        /// <remarks/>
        public int Nvram {
            get {
                return this.nvramField;
            }
            set {
                this.nvramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NvramSpecified {
            get {
                return this.nvramFieldSpecified;
            }
            set {
                this.nvramFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Property {
        
        private object itemField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BooleanValue", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("DecimalValue", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("IntegerValue", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("StringValue", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Peripheral {
        
        private List<Property> propertyField = new List<Property>();
        
        private string hardwareTypeField;
        
        private string hardwareDescriptionPatternField;
        
        private bool notField;
        
        public Peripheral() {
            this.notField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public List<Property>  Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HardwareType {
            get {
                return this.hardwareTypeField;
            }
            set {
                this.hardwareTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HardwareDescriptionPattern {
            get {
                return this.hardwareDescriptionPatternField;
            }
            set {
                this.hardwareDescriptionPatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Not {
            get {
                return this.notField;
            }
            set {
                this.notField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Peripherals {
        
        private List<Peripheral> peripheralField = new List<Peripheral>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Peripheral")]
        public List<Peripheral>  Peripheral {
            get {
                return this.peripheralField;
            }
            set {
                this.peripheralField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BrainBox {
        
        private List<BrainBoxVersion> disallowedVersionField = new List<BrainBoxVersion>();
        
        private string cpuCountField;
        
        public BrainBox() {
            this.cpuCountField = "2";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DisallowedVersion")]
        public List<BrainBoxVersion>  DisallowedVersion {
            get {
                return this.disallowedVersionField;
            }
            set {
                this.disallowedVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("2")]
        public string CpuCount {
            get {
                return this.cpuCountField;
            }
            set {
                this.cpuCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum BrainBoxVersion {
        
        /// <remarks/>
        AVP2_0,
        
        /// <remarks/>
        AVP2_5,
        
        /// <remarks/>
        AVP3_0,
        
        /// <remarks/>
        AVP4_0,
        
        /// <remarks/>
        AVP4_0L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Monitor {
        
        private List<string> allowedResolutionsField = new List<string>();
        
        private List<string> disallowedResolutionsField = new List<string>();
        
        private List<MonitorType> disallowedTypesField = new List<MonitorType>();
        
        private int idField;
        
        private MonitorType typeField;
        
        private bool typeFieldSpecified;
        
        private DisplayType displayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Resolution", IsNullable=false)]
        public List<string>  AllowedResolutions {
            get {
                return this.allowedResolutionsField;
            }
            set {
                this.allowedResolutionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Resolution", IsNullable=false)]
        public List<string>  DisallowedResolutions {
            get {
                return this.disallowedResolutionsField;
            }
            set {
                this.disallowedResolutionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public List<MonitorType>  DisallowedTypes {
            get {
                return this.disallowedTypesField;
            }
            set {
                this.disallowedTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MonitorType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DisplayType Display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum MonitorType {
        
        /// <remarks/>
        MLD,
        
        /// <remarks/>
        CrystalCore,
        
        /// <remarks/>
        Ultrawide,
        
        /// <remarks/>
        CatalinaUltrawide,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum DisplayType {
        
        /// <remarks/>
        IGT_primary,
        
        /// <remarks/>
        IGT_secondary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hardware {
        
        private List<Monitor> monitorsField = new List<Monitor>();
        
        private List<string> videoCardField = new List<string>();
        
        private BrainBox brainBoxField;
        
        private Peripherals peripheralsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<Monitor>  Monitors {
            get {
                return this.monitorsField;
            }
            set {
                this.monitorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DisallowedModel", IsNullable=false)]
        public List<string>  VideoCard {
            get {
                return this.videoCardField;
            }
            set {
                this.videoCardField = value;
            }
        }
        
        /// <remarks/>
        public BrainBox BrainBox {
            get {
                return this.brainBoxField;
            }
            set {
                this.brainBoxField = value;
            }
        }
        
        /// <remarks/>
        public Peripherals Peripherals {
            get {
                return this.peripheralsField;
            }
            set {
                this.peripheralsField = value;
            }
        }
    }
}
