//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace IGT.Game.Core.Communication.Standalone.Schemas {
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SystemConfigurations {
        
        private List<PaytableListPaytableConfiguration> paytableListField = new List<PaytableListPaytableConfiguration>();
        
        private FoundationOwnedSettings foundationOwnedSettingsField;
        
        private SystemControlledProgressives systemControlledProgressivesField;
        
        private GameSubModeType gameSubModeTypeField;
        
        private TournamentSessionConfiguration tournamentSessionConfigurationField;
        
        private StompBrokerConfiguration stompBrokerConfigurationField;
        
        private SystemProgressiveSimulator systemProgressiveSimulatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PaytableConfiguration", IsNullable=false)]
        public List<PaytableListPaytableConfiguration>  PaytableList {
            get {
                return this.paytableListField;
            }
            set {
                this.paytableListField = value;
            }
        }
        
        /// <remarks/>
        public FoundationOwnedSettings FoundationOwnedSettings {
            get {
                return this.foundationOwnedSettingsField;
            }
            set {
                this.foundationOwnedSettingsField = value;
            }
        }
        
        /// <remarks/>
        public SystemControlledProgressives SystemControlledProgressives {
            get {
                return this.systemControlledProgressivesField;
            }
            set {
                this.systemControlledProgressivesField = value;
            }
        }
        
        /// <remarks/>
        public GameSubModeType GameSubModeType {
            get {
                return this.gameSubModeTypeField;
            }
            set {
                this.gameSubModeTypeField = value;
            }
        }
        
        /// <remarks/>
        public TournamentSessionConfiguration TournamentSessionConfiguration {
            get {
                return this.tournamentSessionConfigurationField;
            }
            set {
                this.tournamentSessionConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public StompBrokerConfiguration StompBrokerConfiguration {
            get {
                return this.stompBrokerConfigurationField;
            }
            set {
                this.stompBrokerConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public SystemProgressiveSimulator SystemProgressiveSimulator {
            get {
                return this.systemProgressiveSimulatorField;
            }
            set {
                this.systemProgressiveSimulatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PaytableListPaytableConfiguration : PaytableBinding {
        
        private bool isDefaultField;
        
        /// <remarks/>
        public PaytableListPaytableConfiguration() {
            this.isDefaultField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaytableBinding {
        
        private string themeIdentifierField;
        
        private string paytableIdentifierField;
        
        private string paytableNameField;
        
        private string paytableFileNameField;
        
        private PaytablePayvarType payvarTypeField;
        
        private uint denominationField;
        
        private ulong buttonPanelMinBetField;
        
        private bool buttonPanelMinBetFieldSpecified;
        
        private ulong maxBetField;
        
        private bool maxBetFieldSpecified;
        
        /// <remarks/>
        public PaytableBinding() {
            this.payvarTypeField = PaytablePayvarType.Standard;
        }
        
        /// <remarks/>
        public string ThemeIdentifier {
            get {
                return this.themeIdentifierField;
            }
            set {
                this.themeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string PaytableIdentifier {
            get {
                return this.paytableIdentifierField;
            }
            set {
                this.paytableIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string PaytableName {
            get {
                return this.paytableNameField;
            }
            set {
                this.paytableNameField = value;
            }
        }
        
        /// <remarks/>
        public string PaytableFileName {
            get {
                return this.paytableFileNameField;
            }
            set {
                this.paytableFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(PaytablePayvarType.Standard)]
        public PaytablePayvarType PayvarType {
            get {
                return this.payvarTypeField;
            }
            set {
                this.payvarTypeField = value;
            }
        }
        
        /// <remarks/>
        public uint Denomination {
            get {
                return this.denominationField;
            }
            set {
                this.denominationField = value;
            }
        }
        
        /// <remarks/>
        public ulong ButtonPanelMinBet {
            get {
                return this.buttonPanelMinBetField;
            }
            set {
                this.buttonPanelMinBetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ButtonPanelMinBetSpecified {
            get {
                return this.buttonPanelMinBetFieldSpecified;
            }
            set {
                this.buttonPanelMinBetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ulong MaxBet {
            get {
                return this.maxBetField;
            }
            set {
                this.maxBetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxBetSpecified {
            get {
                return this.maxBetFieldSpecified;
            }
            set {
                this.maxBetFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PaytablePayvarType {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Tournament,
        
        /// <remarks/>
        PayvarGroupTemplate,
        
        /// <remarks/>
        SingleMultiTemplate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Version {
        
        private uint majorField;
        
        private uint minorField;
        
        /// <remarks/>
        public Version() {
            this.majorField = ((uint)(1));
            this.minorField = ((uint)(0));
        }
        
        /// <remarks/>
        public uint Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public uint Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BonusSoaaSettingsType {
        
        private bool supportedField;
        
        private bool isAllowedField;
        
        private int minDelaySecondsField;
        
        /// <remarks/>
        public bool Supported {
            get {
                return this.supportedField;
            }
            set {
                this.supportedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAllowed {
            get {
                return this.isAllowedField;
            }
            set {
                this.isAllowedField = value;
            }
        }
        
        /// <remarks/>
        public int MinDelaySeconds {
            get {
                return this.minDelaySecondsField;
            }
            set {
                this.minDelaySecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarketingBehaviorType {
        
        private TopScreenGameAdvertisementType topScreenGameAdvertisementField;
        
        private bool topScreenGameAdvertisementFieldSpecified;
        
        /// <remarks/>
        public TopScreenGameAdvertisementType TopScreenGameAdvertisement {
            get {
                return this.topScreenGameAdvertisementField;
            }
            set {
                this.topScreenGameAdvertisementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TopScreenGameAdvertisementSpecified {
            get {
                return this.topScreenGameAdvertisementFieldSpecified;
            }
            set {
                this.topScreenGameAdvertisementFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TopScreenGameAdvertisementType {
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        Promo,
        
        /// <remarks/>
        Paytable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FoundationOwnedSettings {
        
        private List<EnvironmentAttributeString> environmentAttributeField = new List<EnvironmentAttributeString>();
        
        private long gameMinBetField;
        
        private bool gameMinBetFieldSpecified;
        
        private WinCapBehaviorType winCapBehaviorField;
        
        private bool winCapBehaviorFieldSpecified;
        
        private long winCapLimitField;
        
        private bool winCapLimitFieldSpecified;
        
        private uint winCapMultiplierField;
        
        private bool winCapMultiplierFieldSpecified;
        
        private long progressiveWinCapLimitField;
        
        private bool progressiveWinCapLimitFieldSpecified;
        
        private long totalWinCapLimitField;
        
        private bool totalWinCapLimitFieldSpecified;
        
        private long transferBankToWagerableField;
        
        private bool transferBankToWagerableFieldSpecified;
        
        private uint maxHistoryStepsField;
        
        private FoundationOwnedSettingsCreditFormatter creditFormatterField;
        
        private FoundationOwnedSettingsAncillarySetting ancillarySettingField;
        
        private AutoPlayConfigurationType autoPlayConfigurationField;
        
        private bool autoPlayConfigurationFieldSpecified;
        
        private bool autoPlayConfirmationRequiredField;
        
        private bool autoPlayConfirmationRequiredFieldSpecified;
        
        private bool autoPlaySpeedIncreaseAllowedField;
        
        private bool autoPlaySpeedIncreaseAllowedFieldSpecified;
        
        private bool displayVideoReelsForStepperField;
        
        private bool displayVideoReelsForStepperFieldSpecified;
        
        private string jurisdictionField;
        
        private uint minimumBaseGamePresentationTimeField;
        
        private bool minimumBaseGamePresentationTimeFieldSpecified;
        
        private uint minimumFreeSpinTimeField;
        
        private bool minimumFreeSpinTimeFieldSpecified;
        
        private CreditMeterBehaviorType creditMeterBehaviorField;
        
        private bool creditMeterBehaviorFieldSpecified;
        
        private bool roundWagerUpPlayoffEnabledField;
        
        private bool roundWagerUpPlayoffEnabledFieldSpecified;
        
        private MarketingBehaviorType marketingBehaviorField;
        
        private BonusSoaaSettingsType bonusSoaaSettingsField;
        
        private bool rtpOrderedByBetRequiredField;
        
        private bool rtpOrderedByBetRequiredFieldSpecified;
        
        /// <remarks/>
        public FoundationOwnedSettings() {
            this.maxHistoryStepsField = ((uint)(50));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnvironmentAttribute")]
        public List<EnvironmentAttributeString>  EnvironmentAttribute {
            get {
                return this.environmentAttributeField;
            }
            set {
                this.environmentAttributeField = value;
            }
        }
        
        /// <remarks/>
        public long GameMinBet {
            get {
                return this.gameMinBetField;
            }
            set {
                this.gameMinBetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GameMinBetSpecified {
            get {
                return this.gameMinBetFieldSpecified;
            }
            set {
                this.gameMinBetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public WinCapBehaviorType WinCapBehavior {
            get {
                return this.winCapBehaviorField;
            }
            set {
                this.winCapBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WinCapBehaviorSpecified {
            get {
                return this.winCapBehaviorFieldSpecified;
            }
            set {
                this.winCapBehaviorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long WinCapLimit {
            get {
                return this.winCapLimitField;
            }
            set {
                this.winCapLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WinCapLimitSpecified {
            get {
                return this.winCapLimitFieldSpecified;
            }
            set {
                this.winCapLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint WinCapMultiplier {
            get {
                return this.winCapMultiplierField;
            }
            set {
                this.winCapMultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WinCapMultiplierSpecified {
            get {
                return this.winCapMultiplierFieldSpecified;
            }
            set {
                this.winCapMultiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long ProgressiveWinCapLimit {
            get {
                return this.progressiveWinCapLimitField;
            }
            set {
                this.progressiveWinCapLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProgressiveWinCapLimitSpecified {
            get {
                return this.progressiveWinCapLimitFieldSpecified;
            }
            set {
                this.progressiveWinCapLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long TotalWinCapLimit {
            get {
                return this.totalWinCapLimitField;
            }
            set {
                this.totalWinCapLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalWinCapLimitSpecified {
            get {
                return this.totalWinCapLimitFieldSpecified;
            }
            set {
                this.totalWinCapLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long TransferBankToWagerable {
            get {
                return this.transferBankToWagerableField;
            }
            set {
                this.transferBankToWagerableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransferBankToWagerableSpecified {
            get {
                return this.transferBankToWagerableFieldSpecified;
            }
            set {
                this.transferBankToWagerableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "50")]
        public uint MaxHistorySteps {
            get {
                return this.maxHistoryStepsField;
            }
            set {
                this.maxHistoryStepsField = value;
            }
        }
        
        /// <remarks/>
        public FoundationOwnedSettingsCreditFormatter CreditFormatter {
            get {
                return this.creditFormatterField;
            }
            set {
                this.creditFormatterField = value;
            }
        }
        
        /// <remarks/>
        public FoundationOwnedSettingsAncillarySetting AncillarySetting {
            get {
                return this.ancillarySettingField;
            }
            set {
                this.ancillarySettingField = value;
            }
        }
        
        /// <remarks/>
        public AutoPlayConfigurationType AutoPlayConfiguration {
            get {
                return this.autoPlayConfigurationField;
            }
            set {
                this.autoPlayConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoPlayConfigurationSpecified {
            get {
                return this.autoPlayConfigurationFieldSpecified;
            }
            set {
                this.autoPlayConfigurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AutoPlayConfirmationRequired {
            get {
                return this.autoPlayConfirmationRequiredField;
            }
            set {
                this.autoPlayConfirmationRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoPlayConfirmationRequiredSpecified {
            get {
                return this.autoPlayConfirmationRequiredFieldSpecified;
            }
            set {
                this.autoPlayConfirmationRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AutoPlaySpeedIncreaseAllowed {
            get {
                return this.autoPlaySpeedIncreaseAllowedField;
            }
            set {
                this.autoPlaySpeedIncreaseAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoPlaySpeedIncreaseAllowedSpecified {
            get {
                return this.autoPlaySpeedIncreaseAllowedFieldSpecified;
            }
            set {
                this.autoPlaySpeedIncreaseAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayVideoReelsForStepper {
            get {
                return this.displayVideoReelsForStepperField;
            }
            set {
                this.displayVideoReelsForStepperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayVideoReelsForStepperSpecified {
            get {
                return this.displayVideoReelsForStepperFieldSpecified;
            }
            set {
                this.displayVideoReelsForStepperFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Jurisdiction {
            get {
                return this.jurisdictionField;
            }
            set {
                this.jurisdictionField = value;
            }
        }
        
        /// <remarks/>
        public uint MinimumBaseGamePresentationTime {
            get {
                return this.minimumBaseGamePresentationTimeField;
            }
            set {
                this.minimumBaseGamePresentationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumBaseGamePresentationTimeSpecified {
            get {
                return this.minimumBaseGamePresentationTimeFieldSpecified;
            }
            set {
                this.minimumBaseGamePresentationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint MinimumFreeSpinTime {
            get {
                return this.minimumFreeSpinTimeField;
            }
            set {
                this.minimumFreeSpinTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumFreeSpinTimeSpecified {
            get {
                return this.minimumFreeSpinTimeFieldSpecified;
            }
            set {
                this.minimumFreeSpinTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CreditMeterBehaviorType CreditMeterBehavior {
            get {
                return this.creditMeterBehaviorField;
            }
            set {
                this.creditMeterBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditMeterBehaviorSpecified {
            get {
                return this.creditMeterBehaviorFieldSpecified;
            }
            set {
                this.creditMeterBehaviorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RoundWagerUpPlayoffEnabled {
            get {
                return this.roundWagerUpPlayoffEnabledField;
            }
            set {
                this.roundWagerUpPlayoffEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoundWagerUpPlayoffEnabledSpecified {
            get {
                return this.roundWagerUpPlayoffEnabledFieldSpecified;
            }
            set {
                this.roundWagerUpPlayoffEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MarketingBehaviorType MarketingBehavior {
            get {
                return this.marketingBehaviorField;
            }
            set {
                this.marketingBehaviorField = value;
            }
        }
        
        /// <remarks/>
        public BonusSoaaSettingsType BonusSoaaSettings {
            get {
                return this.bonusSoaaSettingsField;
            }
            set {
                this.bonusSoaaSettingsField = value;
            }
        }
        
        /// <remarks/>
        public bool RtpOrderedByBetRequired {
            get {
                return this.rtpOrderedByBetRequiredField;
            }
            set {
                this.rtpOrderedByBetRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RtpOrderedByBetRequiredSpecified {
            get {
                return this.rtpOrderedByBetRequiredFieldSpecified;
            }
            set {
                this.rtpOrderedByBetRequiredFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum EnvironmentAttributeString {
        
        /// <remarks/>
        BankedCredits,
        
        /// <remarks/>
        Cds,
        
        /// <remarks/>
        ShowDemo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum WinCapBehaviorType {
        
        /// <remarks/>
        FixedWinCapAmount,
        
        /// <remarks/>
        MultipliedByCurrentBet,
        
        /// <remarks/>
        MultipliedByMaxBet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FoundationOwnedSettingsCreditFormatter {
        
        private string decimalSeparatorField;
        
        private string digitGroupSeparatorField;
        
        private string currencySymbolField;
        
        private string currencyCentSymbolField;
        
        private bool useCreditSeparatorField;
        
        private bool useCreditSeparatorFieldSpecified;
        
        /// <remarks/>
        public string DecimalSeparator {
            get {
                return this.decimalSeparatorField;
            }
            set {
                this.decimalSeparatorField = value;
            }
        }
        
        /// <remarks/>
        public string DigitGroupSeparator {
            get {
                return this.digitGroupSeparatorField;
            }
            set {
                this.digitGroupSeparatorField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCentSymbol {
            get {
                return this.currencyCentSymbolField;
            }
            set {
                this.currencyCentSymbolField = value;
            }
        }
        
        /// <remarks/>
        public bool UseCreditSeparator {
            get {
                return this.useCreditSeparatorField;
            }
            set {
                this.useCreditSeparatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseCreditSeparatorSpecified {
            get {
                return this.useCreditSeparatorFieldSpecified;
            }
            set {
                this.useCreditSeparatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FoundationOwnedSettingsAncillarySetting {
        
        private bool supportedField;
        
        private long cycleLimitField;
        
        private long monetaryLimitField;
        
        /// <remarks/>
        public bool Supported {
            get {
                return this.supportedField;
            }
            set {
                this.supportedField = value;
            }
        }
        
        /// <remarks/>
        public long CycleLimit {
            get {
                return this.cycleLimitField;
            }
            set {
                this.cycleLimitField = value;
            }
        }
        
        /// <remarks/>
        public long MonetaryLimit {
            get {
                return this.monetaryLimitField;
            }
            set {
                this.monetaryLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AutoPlayConfigurationType {
        
        /// <remarks/>
        NotAvailable,
        
        /// <remarks/>
        PlayerInitiatedAvailable,
        
        /// <remarks/>
        HostInitiatedAvailable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CreditMeterBehaviorType {
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        PlayerSelectableDefaultCredits,
        
        /// <remarks/>
        PlayerSelectableDefaultCurrency,
        
        /// <remarks/>
        AlwaysCurrency,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SystemControlledProgressives {
        
        private List<SystemControlledProgressivesProgressiveController> progressiveControllersField = new List<SystemControlledProgressivesProgressiveController>();
        
        private List<SystemControlledProgressivesProgressiveSetup> progressiveSetupsField = new List<SystemControlledProgressivesProgressiveSetup>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProgressiveController", IsNullable=false)]
        public List<SystemControlledProgressivesProgressiveController>  ProgressiveControllers {
            get {
                return this.progressiveControllersField;
            }
            set {
                this.progressiveControllersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProgressiveSetup", IsNullable=false)]
        public List<SystemControlledProgressivesProgressiveSetup>  ProgressiveSetups {
            get {
                return this.progressiveSetupsField;
            }
            set {
                this.progressiveSetupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SystemControlledProgressivesProgressiveController {
        
        private List<SystemControlledProgressivesProgressiveControllerControllerLevel> controllerLevelField = new List<SystemControlledProgressivesProgressiveControllerControllerLevel>();
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ControllerLevel")]
        public List<SystemControlledProgressivesProgressiveControllerControllerLevel>  ControllerLevel {
            get {
                return this.controllerLevelField;
            }
            set {
                this.controllerLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SystemControlledProgressivesProgressiveControllerControllerLevel {
        
        private long startingAmountField;
        
        private long maximumAmountField;
        
        private float contributionPercentageField;
        
        private string prizeStringField;
        
        private bool isEventBasedField;
        
        private bool isEventBasedFieldSpecified;
        
        private int idField;
        
        /// <remarks/>
        public long StartingAmount {
            get {
                return this.startingAmountField;
            }
            set {
                this.startingAmountField = value;
            }
        }
        
        /// <remarks/>
        public long MaximumAmount {
            get {
                return this.maximumAmountField;
            }
            set {
                this.maximumAmountField = value;
            }
        }
        
        /// <remarks/>
        public float ContributionPercentage {
            get {
                return this.contributionPercentageField;
            }
            set {
                this.contributionPercentageField = value;
            }
        }
        
        /// <remarks/>
        public string PrizeString {
            get {
                return this.prizeStringField;
            }
            set {
                this.prizeStringField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEventBased {
            get {
                return this.isEventBasedField;
            }
            set {
                this.isEventBasedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsEventBasedSpecified {
            get {
                return this.isEventBasedFieldSpecified;
            }
            set {
                this.isEventBasedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SystemControlledProgressivesProgressiveSetup {
        
        private PaytableBinding paytableConfigurationField;
        
        private List<SystemControlledProgressivesProgressiveSetupProgressiveLink> progressiveLinkField = new List<SystemControlledProgressivesProgressiveSetupProgressiveLink>();
        
        /// <remarks/>
        public PaytableBinding PaytableConfiguration {
            get {
                return this.paytableConfigurationField;
            }
            set {
                this.paytableConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgressiveLink")]
        public List<SystemControlledProgressivesProgressiveSetupProgressiveLink>  ProgressiveLink {
            get {
                return this.progressiveLinkField;
            }
            set {
                this.progressiveLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SystemControlledProgressivesProgressiveSetupProgressiveLink {
        
        private int gameLevelField;
        
        private string controllerNameField;
        
        private int controllerLevelField;
        
        /// <remarks/>
        public int GameLevel {
            get {
                return this.gameLevelField;
            }
            set {
                this.gameLevelField = value;
            }
        }
        
        /// <remarks/>
        public string ControllerName {
            get {
                return this.controllerNameField;
            }
            set {
                this.controllerNameField = value;
            }
        }
        
        /// <remarks/>
        public int ControllerLevel {
            get {
                return this.controllerLevelField;
            }
            set {
                this.controllerLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GameSubModeType {
        
        private GameSubModeString typeField;
        
        /// <remarks/>
        public GameSubModeType() {
            this.typeField = GameSubModeString.Standard;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(GameSubModeString.Standard)]
        public GameSubModeString Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum GameSubModeString {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Tournament,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TournamentSessionConfiguration {
        
        private long initialCreditsField;
        
        private int countdownDurationField;
        
        private int playDurationField;
        
        private TournamentSessionType sessionTypeField;
        
        /// <remarks/>
        public TournamentSessionConfiguration() {
            this.initialCreditsField = ((long)(0));
            this.countdownDurationField = 0;
            this.playDurationField = 0;
            this.sessionTypeField = TournamentSessionType.Invalid;
        }
        
        /// <remarks/>
        public long InitialCredits {
            get {
                return this.initialCreditsField;
            }
            set {
                this.initialCreditsField = value;
            }
        }
        
        /// <remarks/>
        public int CountdownDuration {
            get {
                return this.countdownDurationField;
            }
            set {
                this.countdownDurationField = value;
            }
        }
        
        /// <remarks/>
        public int PlayDuration {
            get {
                return this.playDurationField;
            }
            set {
                this.playDurationField = value;
            }
        }
        
        /// <remarks/>
        public TournamentSessionType SessionType {
            get {
                return this.sessionTypeField;
            }
            set {
                this.sessionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TournamentSessionType {
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        TimedCredits,
        
        /// <remarks/>
        Credits,
        
        /// <remarks/>
        Timer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StompBrokerConfiguration {
        
        private string hostnameField;
        
        private int portField;
        
        private Version versionField;
        
        /// <remarks/>
        public StompBrokerConfiguration() {
            this.hostnameField = "127.0.0.1";
            this.portField = 61613;
        }
        
        /// <remarks/>
        public string Hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public Version Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SystemProgressiveSimulator {
        
        private bool enabledField;
        
        private bool enabledFieldSpecified;
        
        private int creditsField;
        
        private bool creditsFieldSpecified;
        
        private int contributionFrequencyField;
        
        private bool contributionFrequencyFieldSpecified;
        
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnabledSpecified {
            get {
                return this.enabledFieldSpecified;
            }
            set {
                this.enabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Credits {
            get {
                return this.creditsField;
            }
            set {
                this.creditsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditsSpecified {
            get {
                return this.creditsFieldSpecified;
            }
            set {
                this.creditsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ContributionFrequency {
            get {
                return this.contributionFrequencyField;
            }
            set {
                this.contributionFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContributionFrequencySpecified {
            get {
                return this.contributionFrequencyFieldSpecified;
            }
            set {
                this.contributionFrequencyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PaytableList {
        
        private List<PaytableListPaytableConfiguration> paytableConfigurationField = new List<PaytableListPaytableConfiguration>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PaytableConfiguration")]
        public List<PaytableListPaytableConfiguration>  PaytableConfiguration {
            get {
                return this.paytableConfigurationField;
            }
            set {
                this.paytableConfigurationField = value;
            }
        }
    }
}
