using Logic.Core.Engine;
using Logic.Core.Types;
using Logic.Core.Utility;
using System.Collections;
using System.Collections.Generic;

namespace Game
{
	public class InputSets : IInputSets
	{
		private IReadOnlyList<string> names = new string[] { "Percentage", "Denom", "ProgSetId", "LinesBet", "BetMultiplier" };
		private IReadOnlyList<string> configurationNames = new string[] { "Percentage", "Denom", "ProgSetId" };
		private IReadOnlyList<IReadOnlyList<object>> data = new IReadOnlyList<object>[]
		{
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(1UL) }, new string[] { "P1" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 8L, 10L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(2UL) }, new string[] { "P1" }, new Credits[] { new Credits(50UL) }, new List<long>() { 1L, 2L, 3L, 4L, 5L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(2UL) }, new string[] { "P1" }, new Credits[] { new Credits(50UL) }, new List<long>() { 10L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(5UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(5UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new List<long>() { 6L, 8L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(10UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(10UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new List<long>() { 3L, 4L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(50UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(100UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "NSW01" }, new Money[] { new Money(200UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(1UL) }, new string[] { "P2" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 8L, 10L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(2UL) }, new string[] { "P2" }, new Credits[] { new Credits(50UL) }, new List<long>() { 1L, 2L, 3L, 4L, 5L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(2UL) }, new string[] { "P2" }, new Credits[] { new Credits(50UL) }, new List<long>() { 10L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(5UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(5UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new List<long>() { 6L, 8L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(10UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(10UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new List<long>() { 3L, 4L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(50UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(100UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "NSW02" }, new Money[] { new Money(200UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(1UL) }, new string[] { "P3" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 8L, 10L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(2UL) }, new string[] { "P3" }, new Credits[] { new Credits(50UL) }, new List<long>() { 1L, 2L, 3L, 4L, 5L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(2UL) }, new string[] { "P3" }, new Credits[] { new Credits(50UL) }, new List<long>() { 10L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(5UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(5UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new List<long>() { 6L, 8L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(10UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new List<long>() { 1L, 2L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(10UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new List<long>() { 3L, 4L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(50UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 4L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(100UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "NSW03" }, new Money[] { new Money(200UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "QLD01" }, new Money[] { new Money(50UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "QLD01" }, new Money[] { new Money(100UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "QLD02" }, new Money[] { new Money(50UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "QLD02" }, new Money[] { new Money(100UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "QLD03" }, new Money[] { new Money(50UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L } },
			new object[] { new string[] { "QLD03" }, new Money[] { new Money(100UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(1UL) }, new string[] { "P1" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(2UL) }, new string[] { "P1" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(5UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(10UL) }, new string[] { "P1" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(50UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(100UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS01" }, new Money[] { new Money(200UL) }, new string[] { "P1" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(1UL) }, new string[] { "P2" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(2UL) }, new string[] { "P2" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(5UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(10UL) }, new string[] { "P2" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(50UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(100UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS02" }, new Money[] { new Money(200UL) }, new string[] { "P2" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(1UL) }, new string[] { "P3" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(2UL) }, new string[] { "P3" }, new Credits[] { new Credits(50UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(5UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(10UL) }, new string[] { "P3" }, new Credits[] { new Credits(25UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(50UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(100UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } },
			new object[] { new string[] { "CAS03" }, new Money[] { new Money(200UL) }, new string[] { "P3" }, new Credits[] { new Credits(1UL), new Credits(2UL), new Credits(3UL), new Credits(4UL), new Credits(5UL) }, new long[] { 1L, 2L, 3L, 5L, 10L } }
		};
		private IReadOnlyList<int> startIndexes = new int[] { 0, 6, 11, 12, 16, 18, 20, 22, 42, 52, 57, 63, 68, 69, 73, 75, 77, 79, 99, 109, 114, 120, 125, 126, 130, 132, 134, 136, 156, 166, 171, 181, 186, 196, 201, 211, 216, 221, 226, 231, 236, 261, 286, 311, 316, 321, 326, 331, 356, 381, 406, 411, 416, 421, 426, 451, 476 };
		private IReadOnlyList<Credits> totalBets = new Credits[]
		{
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(400UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(8UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(12UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(16UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(20UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(400UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(8UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(12UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(16UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(20UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(400UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(200UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(100UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(8UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(12UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(16UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(20UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(4UL),
			new Credits(5UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(50UL),
			new Credits(100UL),
			new Credits(150UL),
			new Credits(250UL),
			new Credits(500UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(75UL),
			new Credits(125UL),
			new Credits(250UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL),
			new Credits(1UL),
			new Credits(2UL),
			new Credits(3UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(2UL),
			new Credits(4UL),
			new Credits(6UL),
			new Credits(10UL),
			new Credits(20UL),
			new Credits(3UL),
			new Credits(6UL),
			new Credits(9UL),
			new Credits(15UL),
			new Credits(30UL),
			new Credits(4UL),
			new Credits(8UL),
			new Credits(12UL),
			new Credits(20UL),
			new Credits(40UL),
			new Credits(5UL),
			new Credits(10UL),
			new Credits(15UL),
			new Credits(25UL),
			new Credits(50UL)
		};
		private Cycles initialCycles = Cycles.CreateInitial("Base");

		public int GetCount() { return 57; }
		public int GetInputCount() { return 5; }
		public IReadOnlyList<string> GetInputNames() { return names; }
		public IReadOnlyList<string> GetConfigurationInputNames() { return configurationNames; }

		public IReadOnlyList<object> GetInputValues(int inputSetIndex, int inputIndex)
		{
			var objects = new List<object>();
			var list = (IList)data[inputSetIndex][inputIndex];
			foreach (var o in list)
				objects.Add((object)o);
			return objects;
		}

		public Inputs GetInputs(int inputSetIndex, IReadOnlyList<int> selections)
		{
			var row = new IList[5];
			var lengths = new int[5];
			var inputSet = data[inputSetIndex];

			for (var i = 0; i < 5; i++)
			{
				var list = (IList)inputSet[i];
				row[i] = list;
				lengths[i] = list.Count;
			}

			var totalBet = totalBets[startIndexes[inputSetIndex] + lengths.ToIndex(selections)];
			var denom = (Money)row[1][selections[1]];

			return new Inputs(new Input[]
			{
				new Input("Percentage", row[0][selections[0]]),
				new Input("Denom", row[1][selections[1]]),
				new Input("ProgSetId", row[2][selections[2]]),
				new Input("LinesBet", row[3][selections[3]]),
				new Input("BetMultiplier", row[4][selections[4]]),
				new Input("TotalBet", totalBet),
				new Input("TotalBetAsMoney", totalBet.ToMoney(denom)),
				new Input("Cycles", initialCycles)
			});
		}
	}
}
